version: "3.9"
services:
  frontend:
    build: ./Frontend/
    volumes:
      - ./Frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
